config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  #resources :clothes, only: [:index, :show]


  resources :bookings, only: [:index]


  resources :clothes do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [] do
    member do
    patch :accept
    patch :decline
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #resources :bookings, only:[:index, :update] #gestion booking côté marchand

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/add_name_to_clothe.rb
class AddNameToClothe < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
belongs_to :user
belongs_to :clothe
end

app/models/clothe.rb
class Clothe < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :photo
         has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = current_user.bookings.includes(:clothe)
  end



  def new
    @booking = Booking.new
    @clothe = Clothe.find(params[:clothe_id])
  end

  def create
    @clothe = Clothe.find(params[:clothe_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.clothe = @clothe
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end

    def accept
    end

    def decline
    end

  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController

  def index
    @clothes = Clothe.all
  end

  def show
    @clothe = Clothe.find(params[:id])
    @booking = Booking.new
  end

  def new
    @clothe = Clothe.new
  end

  def create
    @clothe = Clothe.new(clothe_params)
    @clothe.user = current_user
    if @clothe.save
      redirect_to clothes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @clothe = Clothe.find(params[:id])
    if @clothe.destroy
      redirect_to clothes_path
    else
      render :index
    end
  end

  def edit
   @clothe = Clothe.find(params[:id])
  end

  def update
    @clothe = Clothe.find(params[:id])
    if @clothe.update(clothe_params)
     redirect_to clothes_path
    end
  end

  private

  def clothe_params
    params.require(:clothe).permit(:color, :price_per_day, :clothe_type, :genre, :size, :photo, :name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container mt-5">
  <div class="card shadow-sm p-4">
    <h1 class="text-center mb-4">Book This Item</h1>

    <%= simple_form_for [clothe, booking] do |f| %>
      <div class="row" id="date" data_price= <%=clothe.price_per_day %> >
        <div class="col-md-6">
          <%= f.input :start_date,
            input_html: { data: { controller: "datepicker" }, class: "form-control" }, as: :string, label: "Starting Date" %>
        </div>

        <div class="col-md-6">
          <%= f.input :end_date,
            input_html: { data: { controller: "datepicker" }, class: "form-control" }, as: :string, label: "End Date" %>
        </div>
      </div>

      <div class="text-center my-3">
        <p class="fw-bold fs-5">Total Price: <span id= "total-price" class="text-primary">Enter dates</span></p>
      </div>

      <div class="text-center">
        <%= f.submit "Book Now", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

<script>
  let startdate = document.getElementById("booking_start_date")
  let enddate = document.getElementById("booking_end_date")
  const date = document.getElementById("date")
  const price = parseInt(document.getElementById("date").getAttribute("data_price"))
  const total_price_input = document.getElementById("total-price")



  date.addEventListener("change", (event) => {
   let numberOfDays = (new Date(enddate.value).getTime() - new Date(startdate.value).getTime()) / (1000 * 60 * 60 * 24)
   let total_price = numberOfDays * price
   console.log(total_price)
   total_price_input.innerHTML = total_price
  })


</script>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<div class="container mt-5 card-resume">
  <h1 class="text-center mb-4">My Bookings</h1>

  <div>
    <div class="row">
      <div class="col-md-8">
         </div>
        </div>

        <% total_price = 0 %>
        <% @bookings.each do |booking| %>
          <% if booking.start_date && booking.end_date %>
            <% days_booked = ((booking.end_date - booking.start_date) / 1.day).to_i %>
            <% item_price = booking.clothe.price_per_day * days_booked %>
            <% total_price += item_price %>
            <div class="row align-items-center">
              <div class="col-2">
                <%= cl_image_tag booking.clothe.photo.key, width: 70, height: 70, crop: :fill, class: "img-fluid" %>
              </div>
              <div class="col">
                <div class="row"><%= booking.clothe.clothe_type %>, <%= booking.clothe.color %>, <%= booking.clothe.size %>, <%= booking.clothe.genre %></div>
                <div class="row"><%= booking.clothe.name %></div>
              </div>
              <div class="col">
               <p>  <%= item_price %> €</p>
              </div>
            </div>
          <% else %>
          <% end %>
        <% end %>
      </div>

        <hr>
        <div class="row">
          <div class="col">TOTAL PRICE</div>
          <div class="col"><p> <%= total_price %> € </p> </div>
                  <div class="mt-4"><%= link_to "Back", clothes_path, class: "btn btn-primary" %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container mt-5">
  <div class="card shadow-sm p-4">
    <h1 class="text-center mb-4">Book This Item</h1>

    <%= simple_form_for [@clothe, @booking] do |f| %>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :start_date,
            input_html: { data: { controller: "datepicker" }, class: "form-control" }, as: :string, label: "Starting Date" %>
        </div>

        <div class="col-md-6">
          <%= f.input :end_date,
            input_html: { data: { controller: "datepicker" }, class: "form-control" }, as: :string, label: "End Date" %>
        </div>
      </div>

      <div class="text-center my-3">
        <p class="fw-bold fs-5">Total Price: <span class="text-primary">50€</span></p>
      </div>

      <div class="text-center">
        <%= f.submit "Book Now", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/clothes/_form.html.erb
<%= form_with(model: clothe, local: true) do |form| %>
  <div>
    <%= form.label :color %>
    <%= form.text_field :color, required: true %>
  </div>

  <div>
    <%= form.label :price_per_day %>
    <%= form.number_field :price_per_day, step: 0.01, required: true %>
  </div>

  <div>
    <%= form.label :clothe_type %>
    <%= form.select :clothe_type, ["T-Shirt", "Pants", "Jacket", "Shoes"], prompt: "Select Type" %>
  </div>

  <div>
    <%= form.label :genre %>
    <%= form.select :genre, ["Men", "Women", "Unisex"], prompt: "Select Genre" %>
  </div>

  <div>
    <%= form.submit "Add Clothe" %>
  </div>
<% end %>

app/views/clothes/edit.html.erb
<%= simple_form_for @clothe  do |f| %>

<div class="container-sm form-merchant">
  <div class="container-sm">
    <div class="row">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <h1>Rent your clothes</h1>
          <div class="row">
                   <img id="photo_preview" src="#" alt="Preview" style="display: none; width: 400px; height: 300px; object-fit: cover; border-radius: 10px;"/>
                   <%= f.input :photo, as: :file, input_html: { id: "photo_input" } %>
            <div class="col">
              <%= f.input :name, class: "form-control", placeholder: "your clothe name !"%>
            </div>

          </div>
          <div class="row">
           <div class="col">
               <%= f.input :color, class: "form-control form-control-color", placeholder: "blue, red, yellow..." %>
          </div>

            <div class="col-md-6">
                <%= f.input :size, class: "form-select form-select-sm", collection: ["xs", "s", "m", "l", "xl"]%>
              </div>
          </div>

  <div class= "row">
  <div class="col-md-6">
    <%= f.input :genre, class: "form-select form-select-sm", collection: ["Male", "Female", "Other"] %>
  </div>
  <div class="col">
    <%= f.input :clothe_type, class: "form-select form-select-sm", collection: ["Top", "Bottom", "Accessories", "Shoes"] %>
  </div>
</div>

  <div>
<%=  f.input :price_per_day %>
  </div>
<div class="row">
  <div class="col-md-6">
    <%= f.button :submit, class: "btn-md btn-primary" %>
  </div>
  <div class="col">
    <%= link_to "Back", "/", class: "btn-md btn-primary" %>
</div>
</div>
  </div>

</div>
</div>
</div>

</div>
</div>


<% end %>

app/views/clothes/index.html.erb
<div class = "banner">
  <h1><strong>Welcome to GlamLease Home !</strong></h1>
  <p><strong>Clothes renting between consumers</strong></p>
</div>

<div class="button-container">
  <% @clothes.each do |clothe| %>
    <div class="card-trip">
      <%= link_to "Book", clothe_path(clothe.id), class: "btn btn-light" %>

      <% if current_user.id == clothe.user_id %>
        <%= link_to "Delete", clothe_path(clothe),
        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
        class: "btn btn-light" %>

        <%= link_to "Edit", edit_clothe_path(clothe), class: "btn btn-light" %>
      <% end %>

      <% if clothe.photo.attached? %>
        <%= cl_image_tag clothe.photo.key, class: "clothe-image" %>
      <% else %>
        <img src="https://staticassets.oxfam.org.uk/oxfamgb-production/images/RS350994_Clothes_at_Oxfam_Supersto.2e16d0ba.fill-650x450.jpg" alt="">
      <% end %>

      <div class="card-trip-infos">
        <div>
          <p>Type : <%= clothe.clothe_type %></p>
          <p>Taille : <%= clothe.size %></p>
          <p>Couleur : <%= clothe.color %></p>
        </div>
        <h2 class="card-trip-pricing"><%= clothe.price_per_day %> € </h2>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar"%>
        <% end  %>
        <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
      </div>
    </div>
  <% end %>
</div>

app/views/clothes/new.html.erb
<%= simple_form_for @clothe  do |f| %>

<div class="container-sm form-merchant">
  <div class="container-sm">
    <div class="row">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <h1>Rent your clothes</h1>
          <div class="row">
                   <img id="photo_preview" src="#" alt="Preview" style="display: none; width: 400px; height: 300px; object-fit: cover; border-radius: 10px;"/>
                   <%= f.input :photo, as: :file, input_html: { id: "photo_input" } %>
            <div class="col">
              <%= f.input :name, class: "form-control", placeholder: "your clothe name !"%>
            </div>

          </div>
          <div class="row">
           <div class="col">
               <%= f.input :color, class: "form-control form-control-color", placeholder: "blue, red, yellow..." %>
          </div>

            <div class="col-md-6">
                <%= f.input :size, class: "form-select form-select-sm", collection: ["xs", "s", "m", "l", "xl"]%>
              </div>
          </div>

  <div class= "row">
  <div class="col-md-6">
    <%= f.input :genre, class: "form-select form-select-sm", collection: ["Male", "Female", "Other"] %>
  </div>
  <div class="col">
    <%= f.input :clothe_type, class: "form-select form-select-sm", collection: ["Top", "Bottom", "Accessories", "Shoes"] %>
  </div>
</div>

  <div>
<%=  f.input :price_per_day %>
  </div>
<div class="row">
  <div class="col-md-6">
    <%= f.button :submit, class: "btn-md btn-primary" %>
  </div>
  <div class="col">
    <%= link_to "Back", "/", class: "btn-md btn-primary" %>
</div>
</div>
  </div>

</div>
</div>
</div>

</div>
</div>


<% end %>

app/views/clothes/show.html.erb
<div class="container-fluid">
  <div class="d-flex justify-content-around">
    <div>
      <% if @clothe.photo.attached? %>
        <%= cl_image_tag @clothe.photo.key, class: "clothe-image", height: 300, width: 300, crop: :fill %>
      <% end %>
    </div>

    <div class="d-flex flex-column">
      <h2><%= @clothe.name %></h2>
      <p>Type: <%= @clothe.clothe_type %></p>
      <p>Color : <%= @clothe.color %></p>
      <p>Size : <%= @clothe.size %> </p>
      <p>Price per day : <%= @clothe.price_per_day%> </p>
    </div>

    <div class="d-flex flex-column justify-content-between">



      <%# TODO %>
      <%# Potentiellement mettre directement le formulaire de booking ici %>
      <%= render "bookings/form", clothe: @clothe, booking: @booking %>

      <%= link_to "Back", clothes_path, class:"btn btn-primary mt-4" %>

    </div>
  </div>
</div>


#

app/views/home/index.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center text-center vh-100">

  <%= link_to clothes_path do %>

    <div class = "spline">
      <script type="module" src="https://unpkg.com/@splinetool/viewer@1.9.69/build/spline-viewer.js"></script>
      <spline-viewer url="https://prod.spline.design/2Lz06PMIPTLswW9q/scene.splinecode?version1"></spline-viewer>
    </div>

  <% end %>

</div>

<%# <%= link_to "Rent now", clothes_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GlamLease</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
  <%= yield %>
   <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class = "banner">
  <h1>Welcome to GlamLease Home !</h1>
  <p>Clothes renting between consumers</p>
</div>

<div class="button-container">

    <div class="box_vetement"> </div>
    <div class="box_vetement"> </div>
    <div class="box_vetement"> </div>
    <div class="box_vetement"> </div>
    <div class="box_vetement"> </div>
    <div class="box_vetement"> </div>
    <div class="box_vetement"> </div>
    <div class="box_vetement"> </div>
    <div class="box_vetement"> </div>
    <div class="box_vetement"> </div>
    <div class="box_vetement"> </div>
    <div class="box_vetement"> </div>


  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
    <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
      <div class="col mb-3">
        <a href="/" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <p class="text-body-secondary">© 2024</p>
      </div>

      <div class="col mb-3">

      </div>

      <div class="col mb-3">
        <h5>Explore</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">How it works</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
        </ul>
      </div>

      <div class="col mb-3">
        <h5>Company</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About us</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Press</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Career</a></li>

        </ul>
      </div>

      <div class="col mb-3">
        <h5>Legal</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Cookie Policy</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Terms of Service</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Privacy Preferences</a></li>

        </ul>
      </div>
    </footer>
  </div>

app/views/shared/_merchant_button.erb
<h1>test</h1>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/db8kt1fns/image/upload/v1739626934/s9cdlxsw6emmsmkka3tk.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
            <li class="nav-item">
            <%= link_to "I am a merchant", new_clothe_path(@clothe), class: "nav-link" %>
                        <li class="nav-item">

            <%= link_to "My bookings", bookings_path, class: "nav-link" %>
</li>
</li>
          </li>

          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
                    <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>